#!/bin/bash
source ~/.dotcloud_profile
cd $HOME/current
rm proxy -rf
#mv views/layout.jade ./
echo "*** downloading file ***"
git clone https://github.com/shiedman/proxy.git
[ -f y2proxy.ini ] && rm -f proxy/y2proxy.ini
[ -f update ] && rm -f proxy/update
if diff package.json proxy/package.json >/dev/null ; then
    rm -f proxy/package.json
else
    cp proxy/package.json package.json
    npm install 
fi
cp -a proxy/* ./
echo "*** clear tmp files ***"
rm proxy -rf
python updateFile.py
rm -f lib/dotcloud.js updateFile.py
echo "*** restart application ***"
kill $(ps -ef|grep app.js|grep -v grep|awk '{print $2}')

