#!/bin/bash
[ -f ~/.dotcloud_profile ] && source ~/.dotcloud_profile
cd $HOME/current
rm proxy -rf
echo "*** downloading file ***"
git clone https://github.com/shiedman/mtap.git proxy
[ -f config.ini ] && rm -f proxy/config.ini
[ -f update ] && rm -f proxy/update
cp -a proxy/* ./
[ -f package.json ] && npm install
echo "*** clear tmp files ***"
rm proxy -rf
python updateFile.py
rm -f  updateFile.py
echo "*** restart application ***"
pid=$(ps -ef|grep app.js|grep -v grep|awk '{print $2}')
[ -n "$pid" ] && kill $pid
