#!/bin/bash
source ~/.dotcloud_profile
cd $HOME/current
rm proxy -rf
#mv views/layout.jade ./
echo "*** downloading file ***"
git clone https://github.com/shiedman/proxy.git
[ -f y2proxy.ini ] && rm -f proxy/y2proxy.ini
[ -f update ] && rm -f proxy/update
cp -a proxy/* ./
[ -f package.json ] && npm install
echo "*** clear tmp files ***"
rm proxy -rf
python updateFile.py
rm -f  updateFile.py
echo "*** restart application ***"
pid=$(ps -ef|grep app.js|grep -v grep|awk '{print $2}')

if [ -n "$pid" ]; then
    kill $pid
fi
